services:
  frontend:
    build:
      context: ./todo-frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost/api
    container_name: todo-frontend
    volumes:
      - ./todo-frontend:/usr/src/app
  
  backend:
    build: 
      context: ./todo-backend
    container_name: todo-backend
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  
  redis:
    image: redis
    ports:
     - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.d:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.d > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    environment:
      FRONTEND_URL: http://frontend:80/
      BACKEND_URL: http://backend:3000/
    depends_on:
      - frontend
      - backend